### ISSUE TITLE
start proxy automatically

### ISSUE THREAD

**Issue by timokd** [ecovaci/winfoom#1]
add possibillity to give an argument while starting to start proxy immeadiately when launch.bat executes and minimize the app

**Comment by ecovaci** [comment]
It's a good idea and I'll work on it, but there is a small problem here: the proxy host and port are taken by querying  Windows Registry, searching for the system proxy; if the user did not already configured the system proxy, the kind of auto-starting you are proposing is not possible. This case the user should be presented the startup window for the necessary input.
Also, please tell me the kind of proxy are you using (NTML or Kerberos) and if you encountered any issue.

**Comment by ecovaci** [comment]
Won't be fixed: too much hassle for very little gain.

**Comment by jorgeyanesdiez** [comment]
I don't understand why this was closed, what a shame. This program only needs configuration when it's first run. After that, having to wait for the UI to manually click the start button, and then minimize is the REAL hassle.

**Comment by timokd** [comment]
Yes please reopen this issue. It should not be a big effort to implement that but it would help every day a user uses the winfoom proxy. For me it would be very helpful
