### ISSUE TITLE
Crash on VPN disconnect

### ISSUE THREAD

**Issue by philippseith** [ecovaci/winfoom#12]
WinFoom (or the java runtime?) crashed while a Cisco VPN disconnect. The corporate proxy was accessed over this VPN.
For details, see [hs_err_pid30652.log](https://github.com/ecovaci/winfoom/files/10467950/hs_err_pid30652.log)

**Comment by ecovaci** [comment]
I don't think it has something to do with  Cisco VPN disconnect. The AWT layer crashed for some reason. Try to use a LTS JRE version like JRE 17.
Also, try removing some launch arguments by replacing:

> set ARGS=-server -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10 -Dswing.aatext=true -Dspring.profiles.active=gui

with:

> set ARGS=-server -Dswing.aatext=true -Dspring.profiles.active=gui

**Comment by philippseith** [comment]
Ok, I will do that. For the last 3 month I was using winfoom on daily basis over vpn against our corporate proxy. Other than px, which often hung, winfoom ran flawlessly and fast. So I think the crash was really caused by a problem in OpenJDK which was updated by chocolatey on 2023-01-18

**Comment by ecovaci** [comment]
What actually is "px"?

**Comment by philippseith** [comment]
;-)  https://github.com/genotrance/px
