### ISSUE TITLE
Support simultaneously PAC file and system credentials

### ISSUE THREAD

**Issue by CidTori** [ecovaci/winfoom#13]
**Feature request's description**
I need to use both a PAC file *and* system credentials (for security reasons) simultaneously.

**The solution**
I would like the same "Use system credentials" feature from the HTTP proxy type for the PAC proxy type.

**Comment by ecovaci** [comment]
I don't think I understand your request. On Windows, if the Username/Password fields not filled in, the current credentials are used. Why do you need to provide both? How does this improve the security, when  credentials in Winfoom are kept encoded but not encrypted?

**Comment by CidTori** [comment]
When using the GUI and choosing the PAC proxy type, there is no "Use system credentials" checkbox, contrary to the HTTP proxy type, which means, I suppose, that using system credentials is not supported with the PAC proxy type, which means that, since I need to use a PAC file, I have to put my username and password, in plain text, in the configuration file, which isn't great in terms of security.

**Comment by ecovaci** [comment]
That's wrong. In PAC mode, when no credentials are provided, the system credentials are used. Read the tooltip of the Username/Password fields in PAC mode

**Comment by CidTori** [comment]
You are right, I didn't see the tooltip. In that case, why not display the same checkbox as with the HTTP proxy type? It would be harder to miss than the tooltip.
