### ISSUE TITLE
PAC mode not working

### ISSUE THREAD

**Issue by timokd** [ecovaci/winfoom#14]
The proxy .pac file is not working for me. When I give the pass to the pac file and start the proxy there isn't any error message. I tried to start in debug mode but there are no debug messages and no log file was created. So I can't give any detailed error descrition.

**Comment by ecovaci** [comment]
The location of the log is C:\Users\<your username>\.winfoom\logs
Please attach the log in debug mode.

**Comment by timokd** [comment]
Upload always fails

**Comment by ecovaci** [comment]
Post it then.

**Comment by ecovaci** [comment]
Please download the release: https://github.com/ecovaci/winfoom/releases/tag/v2.0.2 and test again.

**Comment by timokd** [comment]
Hello @ecovaci,
PAC mode is working now. Thank you.
Regards Timo

**Comment by ecovaci** [comment]
@timokd Great, I will close this issue. Thank you for your interest to make this application better.
