### ISSUE TITLE
WARNs in log

### ISSUE THREAD

**Issue by PhantomLord72** [ecovaci/winfoom#14]
On my windows 11 machine, in the log there are these 2 lines every second:
26-07-2023 09:55:28.145 [pool-7-thread-42] WARN  o.a.http.impl.auth.HttpAuthenticator.generateAuthResponse - NEGOTIATE authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
26-07-2023 09:55:28.145 [pool-7-thread-42] WARN  o.a.http.impl.auth.HttpAuthenticator.generateAuthResponse - NTLM authentication error: Credentials cannot be used for NTLM authentication: org.apache.http.auth.UsernamePasswordCredentials

Starting FoomApplication v4.0.3 using Java 17.0.2
The following 1 profile is active: "gui"
processPropertySource - Properties location [file:./config/system.properties] not resolvable: .\config\system.properties (Impossibile trovare il file specificato)
26-07-2023 10:00:30.241 [main] INFO  org.kpax.winfoom.config.ProxyConfig.init - Check config directory
26-07-2023 10:00:30.241 [main] INFO  org.kpax.winfoom.config.ProxyConfig.init - Check temp directory
26-07-2023 10:00:30.241 [main] INFO  org.kpax.winfoom.config.ProxyConfig.init - Using temp directory .\out\temp
26-07-2023 10:00:30.241 [main] INFO  org.kpax.winfoom.config.SystemConfig.init - System settings: SystemConfig(maxConnectionsPerRoute=20, maxConnections=600, internalBufferLength=102400, connectionManagerCleanInterval=60, connectionManagerIdleTimeout=100, serverSocketBacklog=1000, socketSoTimeout=65, socketConnectTimeout=20, connectionRequestTimeout=30, preferIPv6Addresses=false, cacheGlobPatternCapacity=100, cacheCredentialsProviderCapacity=100, pacScriptEnginePoolMaxTotal=100, pacScriptEnginePoolMinIdle=20, apiServerRequestTimeout=10, kerberosLoginMinInterval=30, apiDisableShutdown=false, apiReadOnly=false)
Start local proxy server with userConfig ProxyConfig(appVersion=4.0.3, apiPort=9999, apiToken=YWRtaW46d2luZm9vbQ==, proxyType=HTTP, localPort=3128, proxyHttpHost=www.myrealhttp.proxy, proxySocks5Host=, proxySocks4Host=, proxyHttpPort=80, proxySocks5Port=0, proxySocks4Port=0, proxyTestUrl=https://www.google.com, proxySocks5Username=null, proxySocks5Password=null, proxyHttpUsername=mydomain\myuser, proxyHttpPassword=mypassword, useCurrentCredentials=false, proxyPacFileLocation=null, blacklistTimeout=30, proxyPacUsername=null, proxyPacPassword=null, pacHttpAuthProtocol=null, autostart=false, autodetect=false, httpAuthProtocol=BASIC, tempDirectory=.\out\temp)

If I switch on basic authentication or NTLM it works well. But always with these warnings specified in the top of this message

**Comment by ecovaci** [comment]
It is safe to ignore them. The reason for those warnings is quite simple: on handshake phase, the first protocol to try is Kerberos, hence the `(Mechanism level: KrbException)` message and the error since the protocol is actually Basic; then NTLM is employed, another error; only Basic  succeeds.
