### ISSUE TITLE
start and minimize WinFoom with "launch.bat start" parameter

### ISSUE THREAD

**Issue by timokd** [ecovaci/winfoom#18]
Hello @ecovaci,
Due to I've to start several application after Windows start I would like to have a parameter ("start" for example) which I can pass to the launch.bat. This would make the WinFoom start automatically minimized.
In case it would be the first start then it'll start with the normal window because I've to enter the necessary data first and click on start button.   

Is this possible? It would help me and other users a lot.

**Comment by ecovaci** [comment]
This will be solved with the upcoming GUI-less mode.

**Comment by timokd** [comment]
Great news. Thank you. 👍
