### ISSUE TITLE
Clarify how the "Test URL" in the GUI is supposed to work

### ISSUE THREAD

**Issue by sschuberth** [ecovaci/winfoom#20]
**Is your feature request related to a problem? Please describe.**

From just looking at the GUI, it's unclear how the "Test URL" is used.

**Describe the solution you'd like**

I would have expected a separate "Test" button (e.g. to the right of the text field for the URL), which if clicked tests if the given URL can be reached via the selected proxy.

**Describe alternatives you've considered**

*If* the "Test URL" is automatically used to verify proxy information as soon as it is entered, maybe the start button should be grayed out if the test fails. But I'd prefer the explicit approach mentioned above.

**Comment by ecovaci** [comment]
Not sure I correctly understand. Do you propose the test settings to be a separate step, performed before the actual start?

**Comment by sschuberth** [comment]
First I'd like to understand how it's currently supposed to work, because it's really not clear to me. It seems whatever I enter as a "Test URL" has no effect. For example, I can enter a non-existing URL and still click on "Start" just fine.

**Comment by sschuberth** [comment]
From briefly looking at [the code](https://github.com/ecovaci/winfoom/blob/25e273e169b903db894b4242abc9dde0f89e4b2f/src/main/java/org/kpax/winfoom/proxy/ProxyValidator.java#L155-L185) it seems the "Test URL" is used to perform a `GET` request, but the result is only logged, and not visible in the GUI. Displaying the result in the GUI in some way would be nice.

**Comment by ecovaci** [comment]
Like you correctly said, before starting winfoom checks if the given URL can be reached via the selected proxy by issuing a GET request. If the request fails, an appropriate message is shown to the user.  If I enter `http://example.comx` I get an error, so I don't know why you don't get it..

**Comment by ecovaci** [comment]
The only problem I see is the incorrect message, for which I just opened a bug: https://github.com/ecovaci/winfoom/issues/21

**Comment by ecovaci** [comment]
I was able to reproduce 

>  For example, I can enter a non-existing URL and still click on "Start" just fine.

only for HTTP proxy. I'll mark this as a bug, since an error message should pop up instead of starting.

**Comment by ecovaci** [comment]
Solved in 2.1.0
Now the application starts only if the Test URL is valid and reachable.
