### ISSUE TITLE
Winfoom reports "wrong user/password" after password change

### ISSUE THREAD

**Issue by sschuberth** [ecovaci/winfoom#27]
**Bug description**
Winfoom was working fine until I recently had to change my Windows domain password (due to corporate policies). But now I get "Wrong user/password" when pressing start.

**To Reproduce**
1. Open Winfoom
2. Keep using settings that worked before
3. Press "Start"
4. Get "Wrong user/password"

**Expected behavior**
I would Winfoom to continue to work after a domain password change.

**Log**
Interestingly, the issue disappeared when running `launch.bat` with `--debug` in order to get the logs! Afterwards, also just running `launch.bat` again worked. Hence I'm not attaching any logs.

**Context information:**
Winfoom 2.2.1

**Additional context**
I'm still filing this issue in case other users encounter the same thing to document my work-around to make the issue go away again.

**Comment by ecovaci** [comment]
After changing the Windows domain password , the **entire application** needs to be restarted. Restarting the proxy server with Stop/Start buttons is not enough (because the credentials artifacts are cached). I would not tag this as a bug, if you agree I'll tag it as enhancement.

**Comment by sschuberth** [comment]
Hmm, I'm pretty sure I *did* restart the entire application, and I probably even rebooted the PC in between. But I cannot swear blind on it.

**Comment by ecovaci** [comment]
Would you mind testing this? I mean: 

1. With Winfoom running (and the proxy started) change the password again. 
2. Stop the proxy then start it again - you should get "Wrong user/password" error
3. Restart the application and start the proxy - this time should get no error.

**Comment by ecovaci** [comment]
I'm not sure if my previous comment makes sense since a logout/login might be necessary after domain user password change - it is not necessary  for a local user.

**Comment by sschuberth** [comment]
I'll anyway try to reproduce the issue, but it will probably take me a few days as changing our corporate password is a bit cumbersome.

**Comment by ecovaci** [comment]
I did a test with my local account. Interesting, restarting the proxy (without restarting the entire application) was enough to make it work again with a NTLM remote proxy. Anyway, Winfoom delegates the authentication staff to the Apache HttpClient framework which, in turn, makes some (quite expensive) Win32 API calls. That's why it caches the credentials artifacts, at least according to the documentation.

**Comment by ecovaci** [comment]
Closed for lack of activity.

**Comment by sschuberth** [comment]
I also wasn't able to reproduce it lately in order to debug it. If so, I'll reopen.
