### ISSUE TITLE
.msi or .exe installer

### ISSUE THREAD

**Issue by Eimert** [ecovaci/winfoom#28]
**Feature request's description**
Setting up winfoom and making it auto-start is quite some manual labour.

**The solution**
Java 14 provides an experimental packaging utility called [jpackage](https://www.baeldung.com/java14-jpackage). It sounds promising enough to look into, to see if winfoom can be installed automatically with an .exe or .msi installer. Making winfoom launch on startup would also be nice.

**Comment by ecovaci** [comment]
Close for inactivity.
