### ISSUE TITLE
Auto detect proxy settings from the windows configuration

### ISSUE THREAD

**Issue by nicolus** [ecovaci/winfoom#35]
**Feature request's description**
When I switch from home to the office, or from one network to the other, the proxy I need to use changes, which means I have to reconfigure Winfoom everytime. The proxy is already correctly detected by windows when I set "Automactically detect settings" to On in the proxy settings

![image](https://user-images.githubusercontent.com/3315078/95953546-3d845580-0dfa-11eb-90d5-f6f791156e09.png)

So ideally I'd like winfoom to have on "auto" option that uses this.

**The solution**
Px (another proxy facade written in Python) handles this by defaulting to what is define in the `lpszAutoConfigUrl` property of `WINHTTP_CURRENT_USER_IE_PROXY_CONFIG` here : https://github.com/genotrance/px/blob/master/px.py#L1378 .
It will also refresh every x seconds and change the proxy if needed.

Another implementation using C# can be found here : https://stackoverflow.com/a/49441500/1578702

I have exactly zero experience with Java (or networking for that matter), so I'm not sure how it could be implemented in Java unfortunately.

This feature, along with [GUI-less mode](https://github.com/ecovaci/winfoom/issues/19) would mean that one could automatically start winfoom with windows, set all their tools to use 127.0.0.1:3129 as a proxy, and never have to worry about it again !

**Comment by ecovaci** [comment]
A new checkbox labeled "Automatically detect settings" will be added to the application. I will follow Px's approach. Does Winfoom work well for you? Is the performance satisfactory?

**Comment by nicolus** [comment]
Thanks !

> Does Winfoom work well for you? Is the performance satisfactory?

I've been using it at work for a couple of weeks to get my web development tools (phpStorm, POSTman, composer, npm...) to work behind our corporate proxy and so far it's worked flawlessly and I haven't noticed any performance issue 👍 

The only issue I have is that Spotify sometimes switches to offline mode for a minute or so when using it through Winfoom, but I'm really not sure what's happening.

**Comment by ecovaci** [comment]
Solved in [v2.7.0](https://github.com/ecovaci/winfoom/releases/tag/v2.7.0) release. 
Please test this new version in the conditions you described above and post the feedback.

**Comment by ecovaci** [comment]
About Spotify issue, it happened to me also when using it through Winfoom. It seems to be a common issue, here is [the solution](https://community.spotify.com/t5/Desktop-Mac/Offline-error-code-4/td-p/1121138). Worked like a charm to me.

**Comment by nicolus** [comment]
> 
> 
> Solved in [v2.7.0](https://github.com/ecovaci/winfoom/releases/tag/v2.7.0) release.
> Please test this new version in the conditions you described above and post the feedback.

Wow, that was quick !
It seems to work perfectly fine so far, thank you so much !

**Comment by ecovaci** [comment]
You welcome. You have mentioned an issue with Spotify. I was able to figure out why it happens: `socket.soTimeout` value is too small for Spotify, so I increased the value in v2.7.1 Please use this version and give me a feedback if the issue happens again, to adjust this parameter again.

**Comment by ecovaci** [comment]
I opened an issue about Spotify:  https://github.com/ecovaci/winfoom/issues/36
