### ISSUE TITLE
How about support "no proxy for" configuration?

### ISSUE THREAD

**Issue by copbint** [ecovaci/winfoom#37]
**Feature request's description**
Some applications do not support "no proxy for" configuration, and configure ”"no proxy for"“ for every application make me feel frustrated, so it will be amazing if winfoom support this !

**Comment by ecovaci** [comment]
IMO it is conceptually wrong to have a "no proxy for" setting at proxy level. This setting should be at application level because, let's say, application A may want xyz.com URL to go through proxy while application B may want the same URL to go directly.

**Comment by copbint** [comment]
Thanks for you reply!  Yeah, you are right. But work in corporate environments, we need a simple way to set "no proxy for" for all Intranet destinations. And wen can see, cntlm support "NoProxy" option, it's convenient.

**Comment by ecovaci** [comment]
The main reason why I will not implement this is because of the performance penalty. Every single URL has to be parsed, then extract the domain, resolve it against a DNS server to get the IP etc. All these for very little gain in terms of functionality.

**Comment by copbint** [comment]
Ok, get that. Thanks for your wonderful work!

**Comment by ecovaci** [comment]
You welcome.
