### ISSUE TITLE
reduce memory footprint of jvm

### ISSUE THREAD

**Issue by 3rdmaths** [ecovaci/winfoom#38]
**Feature request's description**
Currently no heap size arguments are provided so that default size calculation holds when launching the jvm. On large memory systems (like >8g) this can lead to have huge memory allocation for jvm heap that will be be never used. (In my system around 1g)

**The solution**
Provide minimal and maximal jvm heap size and perm size like : -Xms48m -Xmx48m -XX:MaxMetaspaceSize=48m.

**Alternatives**
none. in launch.bat extended parameters for jvm argmument only takes -D... parameters and not -X... ones

**Additional context**
I'm not expert in jvm , and my first aim was to limit memory footprint to around 64m but, even with the arguments I set, i can only reduce footprint to around 200m that is quite much for a proxy (even a 1000 connections with each 16k cache should takle only around 16m memory, i don't see why so much memory is allocated)
![image](https://user-images.githubusercontent.com/35063911/99496074-eb43d080-2973-11eb-9e59-f6d9de11913e.png)

I would like someone to provide better argument that would reduce the footprint to around 64m.

**Comment by ecovaci** [comment]
"200m that is quite much for a proxy" !?!.  Where did you get the 16k cache size from?

**Comment by 3rdmaths** [comment]
> "200m that is quite much for a proxy" !?!. Where did you get the 16k cache size from?

16k was just a guess, or i have read it somewhere. Any case it'd be the maximum size that i'd like to use for a socket cache.

**Comment by ecovaci** [comment]
The mechanism of a proxy facade is much more complex than you think it is. My advice to you is to leave it as it is now, without modifying the -Xm* Java options.

**Comment by 3rdmaths** [comment]
> The mechanism of a proxy facade is much more complex than you think it is. My advice to you is to leave it as it is now, without modifying the -Xm* Java options.

If I don't use those settings, the proxy starts with 
![image](https://user-images.githubusercontent.com/35063911/99629953-44c20300-2a39-11eb-82b8-28536c7da0ec.png)
and keep raising until 1g of memory, that is too much! seems very likely a memory leak, like objects are not garbaged collected

I prefere limitting the size, until now i had no crash, using it limited.


> "200m that is quite much for a proxy" !?!.

Yes it is. For exemple fiddler proxy that i also use when debugging, is only half that size :
![image](https://user-images.githubusercontent.com/35063911/99630270-db8ebf80-2a39-11eb-8ef1-60252ebc71ed.png)

**Comment by ecovaci** [comment]
From my experience, Winfoom never used more than 300M, even under heavy testing. If you are so concerned about RAM usage, then use an alternative to Winfoom.
