### ISSUE TITLE
Validation failed with status code 500 

### ISSUE THREAD

**Issue by mnisius** [ecovaci/winfoom#4]
**Bug description**
Hi, I just found this project and wanted to try it out. Sadly i was not able to connect to the internet. 
I get this Error Message if I use the Test Button

> Validation failed with status code 500 reason: Proxy Auto Config javascript file: content not acceptable

We use an PAC file. 
With PX Proxy everything working fine out of the box, no config necessary.  

**To Reproduce**
1. Start winfoom in GUI Mode
2. Click autodetect
3. Click start
4. Click test

**Expected behavior**
Success message.

**Log**
I can't attach the log because it contains the full pac file and I don't think I'm allowed to share that. 

**Screenshots**
![Screenshot 2021-12-15 101029](https://user-images.githubusercontent.com/56688244/146164276-30dd3434-6235-4a67-a330-f06128e603b4.png)

**Context information:**
 - Application version v4.0.0
 - JRE version: adoptopenjdk  11.0.12-7

**Additional context**
none

**Comment by ecovaci** [comment]
Please attach the log file in debug mode

**Comment by mnisius** [comment]
Ok here you go. 
I had to remove some stuff. Like I said in the initial post I'm not allowed to share the content of my companies pac file. 

[winfoom.log](https://github.com/ecovaci/winfoom/files/7719471/winfoom.log)

**Comment by ecovaci** [comment]
Please post the pac file without the IP or domain names. I'm only interested in it's structure.

**Comment by ecovaci** [comment]
I'm interested in the lines looking like: PROXY_TYPE IP_LIST_OR_DOMAIN_NAMES. For example `return "PROXY 1.2.3.4:8080"`

**Comment by ecovaci** [comment]
The acceptable values for `PROXY_TYPE` are PROXY, HTTP, HTTPS, SOCKS, SOCKS4, SOCKS5, DIRECT

**Comment by mnisius** [comment]
here the file without ips and domains: removed

edit: I removed the file. If you need it again just tell me.

**Comment by ecovaci** [comment]
Ok, I found the problem: the line `PROXY xxx:8080; PROXY xxx:8080; ` has an extra space. I will trim it in the v4.0.1.

**Comment by ecovaci** [comment]
Please test it and let me know the result.

**Comment by mnisius** [comment]
It worked! 🎉🎉🎉
Thank you very much for your fast fix!

**Comment by NukeAttokurov** [comment]
Good afternoon.
Please help me, I am using the latest version of WinFoom I have a problem with internet access. Installed KNIME, Eclipse, DBeaver all these programs still have problems with Internet access. Please tell me what could be the problem?
![image](https://user-images.githubusercontent.com/99389591/215076393-6cb2108e-2394-400c-9ee6-46c0bc7a28bc.png)

**Comment by ecovaci** [comment]
Did you configure Eclipse to use Winfoom as proxy? I think this is the problem.

**Comment by ecovaci** [comment]
Also, please open a separate issue since your problem has nothing to do with the current one.
