### ISSUE TITLE
Support WSL2

### ISSUE THREAD

**Issue by AlexanderLanin** [ecovaci/winfoom#40]
**Feature request's description**
I've just upgraded to WSL2 and as far as I can tell localhost no longer connects from WSL2 to Windows.

**The solution**
I'm guessing I need to connect through a different ip.

WSL2 offers the Windows IP via:
```
cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.183.177
```

And on Windows it's:
```
ipconfig
[...]
Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::215:5dff:fe2a:9e9%22
   IPv4 Address. . . . . . . . . . . : 192.168.183.177
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
```

However that would only make sense if Winfoom were to actually listen on that ip.

**Alternatives**
All hints I found so far were about running the proxy facade itself within WSL2.

**Comment by ecovaci** [comment]
I don't think I understand your problem. Winfoom does not listen on an IP, it does listen on a port (3129) If your IP is 192.168.183.177, then you should be able to access Winfoom with 192.168.183.177:3129 proxy configuration (given that the address is reachable).
