### ISSUE TITLE
EnableExpansion should say EnableDelayedExpansion

### ISSUE THREAD

**Issue by sschuberth** [ecovaci/winfoom#41]
https://github.com/ecovaci/winfoom/blob/fd4cbb6c85e73535c7bb5af44fa3b8515d53d16b/assets/batch/launchGui.bat#L17

**Comment by ecovaci** [comment]
Right, please make the modification.

**Comment by ecovaci** [comment]
Actually, the script doesn't need EnableDelayedExpansion, probably EnableExtensions is more suitable.
