### ISSUE TITLE
opening with launchGui.bat caused exception

### ISSUE THREAD

**Issue by timokd** [ecovaci/winfoom#45]
Hi @ecovaci ,

when I tried to open launchGui.bat I got the error message that the classes where compiled with a more recent Version of compiler.
I could solve this by correcting in launchGui.bat. Instead if exist .\jdk\bin\javaw I changed to if exist .\jdk\bin\javaw.exe . Then it is working correctly by usind the jdk in the .\jdk folder.

Regards 

Timo

**Comment by ecovaci** [comment]
Please run: `java --version` in a terminal and post the result.

**Comment by ecovaci** [comment]
Anyway, it's clearly a bug, I'll make the correction.

**Comment by ecovaci** [comment]
Fixed in v3.1.1
