### ISSUE TITLE
Update log4j to new version

### ISSUE THREAD

**Issue by onlygecko** [ecovaci/winfoom#5]
Hi,

I wanted to test winfoom but recognized, that the prepackaged release 4.0.1 contains log4j 2.14.1. Is there any chance to upgrade this library easily and release a new version?

Greetings,
Peter

**Comment by ecovaci** [comment]
Hi,
winfoom uses logback for logging, not log4j. If you have found log4j in the prepackaged release it is because some dependencies are probably using it.

**Comment by onlygecko** [comment]
Thanks for the quick response and the explanation.  👍 

I'll check periodically the project and releases. :-)
