### ISSUE TITLE
Support multiple instances with different configurations

### ISSUE THREAD

**Issue by bossqone** [ecovaci/winfoom#53]
**Feature request's description**
I would like to have >= 2 instances of WinFoom running, each with different configuration.
For example:
- first one is using SOCKS5 proxy and listen on port 3129
- second one is using PAC proxy and listen on port 3130

Right now I have to switch proxies when developing our application, because running java application uses SOCKS5 proxy and IntelliJ IDEA uses PAC proxy (for plugins, or pulling gradle dependencies).

**The possible solutions**
- store configuration next to WinFoom executable and not in `<user.home.dir>/.winfoom`?
- ability to load/save custom configuration file from app?

**Comment by ecovaci** [comment]
My idea would be to have an environment variable pointing to the application config directory, something like `WINFOOM_CONFIG` with the default value `<user.home.dir>/.winfoom`

**Comment by ecovaci** [comment]
Solved in v3.3.0
