### ISSUE TITLE
Authentication for PAC protocol

### ISSUE THREAD

**Issue by eitsupi** [ecovaci/winfoom#55]
**Feature request's description**
I am looking for an alternative local proxy software for Linux because the Cntlm does not support PAC.
I want to use the NTLM authentication proxy specified in the PAC file, but winfoom doesn't seem to support that situation.

**The solution**
It would be nice to be able to config like that and use the credentials.

```
{
  "proxyType" : "PAC",
  "proxyPacFileLocation" : null,
  "blacklistTimeout" : 30,
  "localPort" : 3129,
  "proxyTestUrl" : "http://example.com",
  "proxyUsername" : null,
  "proxyPassword" : null,
  "httpAuthProtocol" : null
}
```

**Comment by ecovaci** [comment]
Actually the PAC protocol does not support authentication, for good reasons. Imagine you have 2 proxy servers in your PAC file, each with different credentials. The only way to specify the credentials would be in the PAC file, which is a public file, therefore you have no confidentiality. Also, neither Chrome nor Firefox does support PAC with authentication.

**Comment by ecovaci** [comment]
Even if the credentials are global (unique credentials for all the proxy servers), still doesn't work out-of-the-box because Winfoom needs to know the type of the proxy (NTLM, Kerberos, Socks, etc) and this information is missing from the PAC file.

**Comment by eitsupi** [comment]
@ecovaci Thank you for your quick response.
Thanks to your explanation, I understand why Firefox doesn't ask me the password until I open the web page.

My assumption is that all the proxies listed in the pac file are the same authentication protocol, and I wanted to specify this in winfoom config.

**Comment by ecovaci** [comment]
This is doable. I'll start working on it.

**Comment by ecovaci** [comment]
The [v3.4.0](https://github.com/ecovaci/winfoom/releases/tag/v3.4.0) is out, solving this issue. Please install it, test it and give a feedback.

**Comment by eitsupi** [comment]
The latest release works for me, thanks!

I think this is a good improvement for Cntlm users who want to use PAC files ( ex. https://github.com/genotrance/px/issues/70#issuecomment-600371085 ).
