### ISSUE TITLE
If FOOM_ARGS is defined, launchGui.bat can't add FOOM_ARGS to ARGS successfully

### ISSUE THREAD

**Issue by richardtin** [ecovaci/winfoom#60]
**Bug description**

If `FOOM_ARGS` is defined, `launchGui.bat` can't add `FOOM_ARGS` to `ARGS` successfully

**To Reproduce**
1. Set `FOOM_ARGS` in the System Environment on Windows 10
2. Launch "Command Prompt"
3. Run `launchGui.bat` in the "Command Prompt"
4. See the following error
    ```
    'ARGS' is not recognized as an internal or external command,
    operable program or batch file.
    ```

**Expected behavior**

Should add `FOOM_ARGS` to `ARGS` successfully

**Screenshots**
![FOOM_ARGS-issue](https://user-images.githubusercontent.com/3749207/114960060-dfaff380-9e98-11eb-9828-b6eb78e4952f.png)

**Context information:**
 - Application version: `3.4.2`
 - JRE version: `11.0.5`

**Comment by ecovaci** [comment]
Solved in v3.4.3
